name: augll_project
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  augmented_reality_plugin_wikitude:
    path: ./plugins/augmented_reality_plugin_wikitude/

  cupertino_icons: any
  material_design_icons_flutter: any
  get_it: any
  rxdart: any
  provider: any
  location: any
  path_provider: any



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: any
  json_serializable: any
  build_runner: any

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/vector_images/
    - assets/fonts/
    - assets/wikitude_samples/
    - assets/wikitude_samples/selection_sample/
    - assets/wikitude_samples/selection_sample/assets/
    - assets/wikitude_samples/selection_sample/css/
    - assets/wikitude_samples/selection_sample/js/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
