name: augll_project
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  augmented_reality_plugin_wikitude:
    path: ./plugins/augmented_reality_plugin_wikitude/

  #UI
  material_design_icons_flutter: any
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.0
  mask_text_input_formatter: ^2.3.0
  flutter_spinkit: ^5.1.0
  sliding_up_panel: ^2.0.0+1

  #Core
  flutter_hooks: ^0.18.3
  stacked: ^2.3.6
  stacked_services: ^0.8.22+1
  firebase_core: ^1.17.0
  hive: ^2.2.1
  shared_preferences: ^2.0.15
  dartz: ^0.10.1
  path_provider: ^2.0.11

  #-NetworkLayer
  dio: ^4.0.6
  curl_logger_dio_interceptor: ^0.0.3
  dio_cache_interceptor: ^3.3.0
  cached_network_image: ^3.2.1
  pretty_dio_logger: ^1.1.1
  connectivity_plus: ^2.3.6+1
  requests_inspector: ^2.2.0

  #-DI
  get_it: ^7.2.0
  rxdart: ^0.27.5

  #Utils
  logger:
  validators: ^3.0.0
  bot_toast: ^4.0.2
  device_preview: ^1.1.0
  url_launcher: ^6.1.4
  open_file: ^3.2.1
  intl: ^0.17.0
  app_settings: ^4.1.8
  package_info_plus: ^1.4.2
  permission_handler: ^9.0.0

  #Location
  location: ^4.4.0
  map_launcher: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.9.0
  flutter_lints: ^1.0.0
  build_runner: ^2.1.10
  stacked_generator: ^0.6.2
  change_app_package_name: ^0.1.3
  flutter_launcher_icons_maker: ^0.10.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/svgs/
    - assets/images/icons/
    - assets/images/general/
    - assets/ic_launcher/
    - assets/augll_fonts/
    - assets/wikitude_sample/
    - assets/wikitude_sample/assets/
    - assets/wikitude_sample/css/
    - assets/wikitude_sample/js/

  fonts:
    - family: FrutigerLTArabic
      fonts:
        - asset: assets/augll_fonts/FrutigerLTArabic-45Light.ttf
          weight: 400
        - asset: assets/augll_fonts/FrutigerLTArabic-55Roman.ttf
          weight: 500
        - asset: assets/augll_fonts/FrutigerLTArabic-65Bold.ttf
          weight: 600
        - asset: assets/augll_fonts/FrutigerLTArabic-75Black.ttf
          weight: 700
